### ISSUE TITLE
Is it for the 4.1 version?

### ISSUE THREAD

**Issue by fendi1989** [Cliov/Arsenal#1]
Is this artifact kit for the 4.1 version or 3.14?

**Comment by XZVB12** [comment]
no, not for 4.1. For 3.13 and 3.14.
PS: Tell me why you had to publish this on github? What for ?

**Comment by XZVB12** [comment]
> Is this artifact kit for the 4.1 version or 3.14?

no, not for 4.1. For 3.13 and 3.14.
PS: Tell me why you had to publish this on github? What for ?
